export { default as Home } from './Home'
export { default as About } from './About'
export { default as NotFound } from './NotFound'
export { default as ProductList } from './ProductList'
export { default as ProductDetail } from './ProductDetail'